name: "minishell"
services:
  minishell:
    container_name: "minishell"
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - minishell
    restart: always
networks:
  minishell:
